// shell/src/app/app.component.ts
import {Component, ElementRef, ViewChild} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import {CommunicationHub} from "../services/communication.hub";
import {ICommunicationClient} from "../services/interfaces";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'shell';
  value: string = "shell initial value";
  private readonly client: ICommunicationClient;
  private hub: CommunicationHub;


  constructor() {

    this.hub = new CommunicationHub();

    this.client = this.hub.registerClient();

  }


  ngAfterViewInit(): void {
    let iframe = document.getElementById("reactIframe") as any;

    this.hub.registerIframeBroadcaster(iframe.contentWindow);

    // hub.registerIframeBroadcaster(iframe.contentWindow);

    this.client.subscribe("reactTopic", (value) => {
      this.value = value;

      console.log(value);
    });

  }


  onPublishClick() {
    if (this.client) {
      this.client.publish("shellTopic", this.value);
    }
  }
}

<style>
  main {
    width: 100%;
    min-height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 1rem;
    box-sizing: inherit;
    position: relative;
  }

</style>

<main class="main">
  <div>
    <h1>Hello, {{ title }}</h1>

    <span>Congratulations! Your shell is running. 🎉</span>

    <br/>
    <br/>
    <textarea [value]="value"></textarea>
    <button (click)="onPublishClick()">Publish Shell Topic</button>
<!--    <br/>-->
<!--    <br/>-->
<!--    <span>Angular app</span>-->
<!--    <br/>-->
<!--    <iframe src="http://localhost:56289/"></iframe>-->

    <br/>
    <br/>
    <span>React app</span>
    <br/>
    <iframe id="reactIframe" src="http://localhost:3000/"></iframe>
  </div>
</main>


<router-outlet></router-outlet>

// react-app/src/App.tsx
import './App.css';
import {ICommunicationClient} from "./services/interfaces";
import {CommunicationHub} from "./services/communication.hub";
import {useState} from "react";


function App() {
    const hub: CommunicationHub = (window as any).hub
    hub.registerIframeBroadcaster("http://localhost:3000/", "reactIFrameBroadcaster");
    const client: ICommunicationClient = hub.registerClient("reactCommunicationClient");
    const [text, setText] = useState("react initial text");

    function onValueChanged(event: any) {
        setText(event.target.value);
    }

    return (
        <div className="App" style={{backgroundColor: 'lightblue'}}>
            <span>React child app</span>
            <textarea style={{width: "100%"}} value={text} onChange={onValueChanged}></textarea>

            <button onClick={(): void => {
                client.publish("reactTopic", text);
            }}>Publish</button>

            <button onClick={(): void => {
                client.subscribe("shellTopic", newValue => setText(newValue));
            }}>Subscribe to shell topic</button>
        </div>
    );
}

export default App;
